#! /bin/sh

sxhkd &
polybar main &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color \#4c566a
bspc config active_border_color \#4c566a
bspc config active_border_color \#d8dee9

feh --bg-center /home/dwarez/Pictures/arch.png
